version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "4007:4000"            # backend API
    restart: unless-stopped
    environment:
      DB_HOST: mariadb
      DB_USER: hgmuser
      DB_PASS: hgmpw
      DB_NAME: hgm
      PORT: 4000
      CORS_ORIGINS: https://hgm-gate.webeesign.com,https://hgm-management.webeesign.com,http://localhost:3000,http://localhost:3001
    depends_on:
      - mariadb

  frontend_gate:
    build:
      context: ./frontend_gate
      args:
        VITE_API_URL: https://hgm.webeesign.com
    ports:
      - "3230:3000"            # gate frontend
    restart: unless-stopped
    depends_on:
      - backend

  frontend_management:
    build:
      context: ./frontend_management
      args:
        VITE_API_URL: https://hgm.webeesign.com
    ports:
      - "3231:3000"            # management frontend
    restart: unless-stopped
    depends_on:
      - backend

  mariadb:
    build: ./db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: rootpw
      MARIADB_DATABASE: hgm
      MARIADB_USER: hgmuser
      MARIADB_PASSWORD: hgmpw
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
